### ISSUE TITLE
AppArmor profile plumbing

### ISSUE THREAD

**Issue by aeadio** [void-linux/void-infrastructure#82] opened 2020-08-10 19:46 UTC
@the-maldridge requested I open a ticket here

It would be great to have plumbing in place for good AppArmor profile support in Void. Currently, Void is shipping the upstream profiles, which don't cover a lot of applications.

Ideally Void should provide some distro-specific abstraction profiles which profile makers can leverage, and some place for profile makers to submit new application profiles via PRs.

For shipping application profiles, I see three possibilities,

**Central, large apparmor-void package**

An apparmor-void package would contain distro-specific abstraction profiles, _plus_ all application profiles. Contributors wishing to add AppArmor support to a new application would open a PR against this central package. 

Pros:
- No need to vendor in and maintain config across a large amount of packages.

Cons:
- AppArmor loads all profiles present, so this would quickly balloon to many hundreds of redundant profiles for all users.
- Application profiles are uncoupled from the packages they relate to, making maintenance conceptually problematic -- if the profiles fall out of sync with application updates, who is responsible for maintaining that?

**In-package profiles**

The apparmor package would provide distro-specific abstraction profiles, and directives to load additional profiles from a location such as `/usr/lib/apparmor/`, and then each package is separately responsible for shipping its own application profiles installed at that path. Contributors wishing to add AppArmor support to a new application would open a PR against that application's package.

Pros:
- Simplifies AppArmor usage for all users. A single knob turns on AppArmor, and good coverage for all installed applications is provided out of the box.
- Avoids a ton of unused profiles being installed for all users.
- Promotes application profiles as central parts of packages that should be maintained, encourage testing and updating along with application updates. 

Cons:
- Vendors in additional AppArmor-specific config to be included with, and maintained, as part of many separate packages.
- Elevates AppArmor as a first-class policy in the Void ecosystem. Should packages also be responsible for supplying SELinux policies, and policies for every future MAC subsystem? Is it OK to add maintenance burden to package updates for contributors that do not care about AppArmor? 

**Separate -apparmor packages**

The apparmor package would provide distro-specific abstraction profiles, and directives to load additional profiles from a location such as `/usr/lib/apparmor/`, and then separate -apparmor packages can be provided for each application, which contain only the relevant config in `/usr/lib/apparmor/` for that application.

Pros:
- Avoids a ton of unused profiles being installed for all users.
- No need to vendor in a bunch of AppArmor-specific config in all packages.

Cons:
- Puts the burden on the end user for hunting down and installing potentially hundreds of additional packages for good AppArmor coverage.

This should probably split to a -packages ticket for deliberation after the initial plumbing.

**Comment by the-maldridge** [comment] 2020-08-10 19:50
I would recommend one large repo and then programmatically generated subpkgs.  I do not believe it is a reasonable ask to get every maintainer to update and maintain profiles for their package, so it seems reasonable that there might be a detached AppArmor team that keeps profiles up to date.

**Comment by the-maldridge** [comment] 2020-08-10 19:50
@void-linux/pkg-committers for discussion.

**Comment by ericonr** [comment] 2020-08-10 20:17
> I do not believe it is a reasonable ask to get every maintainer to update and maintain profiles for their package

This makes the setup a bit fragile, it's very easy for regressions to slip by.

In https://lists.debian.org/debian-devel/2017/08/msg00090.html, the idea was to enable AppArmor by default, so any regressions could be caught by package contributors, and the simpler AppArmor profile syntax would allow package maintainers to fix profile themselves instead of depending on a dedicated team.

Somewhere in https://www.apparmor.net/ , it's explained that the project would encourage contribution between distros, which is hard because of distro specific install paths as well as differing versions. For specific profiles packages, we have:

- https://gitlab.com/apparmor/apparmor-profiles/-/tree/master/ubuntu/20.04
- https://salsa.debian.org/apparmor-team/apparmor-profiles-extra

I think OpenSUSE is distributing profiles inside packages? At least https://en.opensuse.org/SDB:AppArmor doesn't list any apparmor-profiles package like Debian does.

I really like the idea, but I don't think it's feasible unless there is buy-in from at least a few maintainers.

Pinging @CameronNemo

**Comment by thypon** [comment] 2020-08-11 03:59
May we have a single repo and enable profiles per app through an xbps hook?

In this case we get both a centralized maintenance and no profiles loaded if the package is not present.

**Comment by ericonr** [comment] 2020-08-11 04:16
That would be an interesting solution. So parse a profile to check if it corresponds to a file that exists in the filesystem, and if positive, copy the profile to `/etc/apparmor.d` ?

**Comment by thypon** [comment] 2020-08-11 10:52
or through symlinks, like with services, but automatically.

**Comment by dm17** [comment] 2022-01-24 20:00
What about a hybrid approach where only the more internet-facing/sensitive things get managed profiles? Or have you all found a nicer / more secure solution? I'm currently investigating running chromium in firejail with apparmor. I'd also like to get a few generic profiles for when I need to run some untrusted code/service in the future.

**Comment by the-maldridge** [comment] 2022-07-10 22:06
Apparmor profiles have been plumbed for quite some time now, closing this issue.

**Closed by the-maldridge** 2022-07-10 22:06 UTC
